title: "STCS TIFR CSS.428.1: Introduction to Theory of Deep Learning (Monsoon 2025)"
author: "Jatin Batra"
email: "jatinbatra50@gmail.com"
description: "Course page for STCS TIFR CSS.428.1 – Introduction to Theory of Deep Learning (Monsoon 2025)"
theme: minima
